spring:
  #mysql
  datasource:
    url: jdbc:mysql://42.193.177.218:3306/socket_test?serverTimezone=Asia/Shanghai&characterEncoding=utf-8&useSSL=false
    username: root
    password: z2122472
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false
  jpa:
    properties:
      hibernate:
        #        format_sql: true
        dialect: club.ovelya.socketsystem.config.MyDialect
        hbm2ddl:
          #自动创建表，模式：create create-drop update validate none
          auto: update
    #        show_sql: true
    open-in-view: true
  data:
    #redis
    redis:
      host: 42.193.177.218
      port: 6379
      password: z2122472
  mail:
    host: smtp.qq.com
    username: ovelya@qq.com
    password: zeglbrnpxgzhbfcf
    default-encoding: UTF-8
server:
  port: 8080
springdoc:
  swagger-ui:
    path: /api-docs